### PR TITLE
Change 0002 Remove SpanData status to approved

### PR DESCRIPTION
**Pull request by bg451**
If an rfc is merged, does that mean it's approved? cc @iredelmeier

### CODE REVIEW

**Comment by carlosalberto** [comment]
> If an rfc is merged, does that mean it's approved?

It *seems* like that is not always the case, but for this specific RFC, it is ;)

**Comment by bogdandrutu** [comment]
Yes based on previous discussions that is not the case, for this I think we are good.

**Comment by bogdandrutu** [comment]
I am waiting for 1 more approval before merging.

**Comment by Oberon00** [comment]
Could the PR title be changed to include the name of the RFC? That way it might get the right people look over that quicker (probably doesn't matter anymore for this PR now, but for the future...).

**Comment by bogdandrutu** [comment]
We have 5/10 approvers, do we need majority for this to merge (>5)?

**Pull request merged**
